services:
  # ── Monitoring ─────────────────────────────────────────────────────────────
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    user: "${UID}:${GID}"
    volumes:
      # - model:/usr/share/model/
      # - grafana_data:/var/lib/grafana
      - ${PWD}/srcs/services/grafana/provisioning:/etc/grafana/provisioning
      - ${PWD}/srcs/services/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/srcs/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - monitoring

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring
  
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ${PWD}/srcs/services/loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/srcs/services/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  # ── MinIO (Data Lake & Artifacts) ──────────────────────────────────────────
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    user: "${UID}:${GID}"
    volumes:
      - mlflow-minio:/data
    networks:
      - postgres_network

  # ── Metrics (MLflow) ───────────────────────────────────────────────────────
  mlflow:
    container_name: mlflow-server
    build:
      context: ./services/mlflow
      dockerfile: Dockerfile
    image: ghcr.io/mlflow/mlflow:v2.17.0
    ports:
      - "${MLFLOW_SERVER_PORT:-5000}:5000"
    expose:
      - 5000
    environment:
      MLFLOW_SERVER_HOST: 0.0.0.0
      MLFLOW_SERVER_PORT: 5000
      BACKEND_STORE_URI: postgresql+psycopg2://mlflow:mlflow@postgres_db:5432/mlflowdb
      # ARTIFACT_ROOT: s3://mlflow-artifacts
      # AWS_ACCESS_KEY_ID: minioadmin
      # AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000

      MLFLOW_USER: ${DB_MLFLOW_USER}
      MLFLOW_PASSWORD: ${DB_MLFLOW_PASSWORD}
      MLFLOW_DB: ${DB_MLFLOW_NAME}
      
      # --default-artifact-root s3://mlflow-artifacts
    command: >
      mlflow server 
      --backend-store-uri postgresql://${DB_MLFLOW_USER}:${DB_MLFLOW_PASSWORD}@postgres:5432/${DB_MLFLOW_NAME}
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0 
      --port 5000
    depends_on:
      postgres:
        condition: service_healthy
      # minio:
      #   condition: service_started
    networks:
      - postgres_network
      - model_network
    volumes:
      - model_artifacts:/mlflow/artifacts

  # ── API ────────────────────────────────────────────────────────────────────
  fastapi:
    container_name: fastapi
    build:
      context: ..
      dockerfile: srcs/api/Dockerfile
    expose:
      - 4243
    ports:
      - "0.0.0.0:4243:4243"
    #user: "${UID}:${GID}"
    volumes:
      - ${PWD}/.venv:/app/.venv
      - model:/app/model/

    networks:
      - model_network

  # ── Gateway ────────────────────────────────────────────────────────────────
  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile

  # ── Database (app) ────────────────────────────────────────────────────────
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    user: "${UID}:${GID}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_contain
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8070:80"
    depends_on:
      - postgres
    networks:
      - postgres_network

  # ── Frontend ───────────────────────────────────────────────────────────────
  streamlite:
    container_name: streamlite
    build:
      context: ./services/streamlite
      dockerfile: Dockerfile

volumes:
  postgres_data:
  mlflow-minio:
  model_artifacts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/srcs/data/artifacts
  model:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/srcs/model
  source_python:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.venv

  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/srcs/data/prometheus
  
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/srcs/data/grafana_data

networks:
  postgres_network:
    driver: bridge
  monitoring:
    driver: bridge
  model_network:
    driver: bridge