
def get_features():
	features = [
		"MainBranch",
		"Age",
		"EdLevel",
		"Employment",
		"WorkExp",
		"LearnCode",
		"LearnCodeAI",
		"YearsCode",
		"DevType",
		"OrgSize",
		"ICorPM",
		"RemoteWork",
		"Industry",
		"Country",
		"Currency",
		"CompTotal",
		"LanguageChoice",
		"LanguageHaveWorkedWith",
		"DatabaseChoice",
		"DatabaseHaveWorkedWith",
		"PlatformChoice",
		"PlatformHaveWorkedWith",
		"WebframeChoice",
		"WebframeHaveWorkedWith",
		"DevEnvsChoice",
		"DevEnvsHaveWorkedWith",
		"AIModelsChoice",
		"AISelect",
		"AIAgents",
	]

	return features



def get_features_answers(feature: str):
	match feature:
		case "LearnCode":
			return [
				"Technical documentation (is generated for/by the tool or system)",
				"Games or coding challenges",
				"Colleague or on-the-job training",
				"Videos (not associated with specific online course or certification)",
				"Online Courses or Certification (includes all media types)",
				"Books / Physical media",
				"Stack Overflow or Stack Exchange",
				"AI CodeGen tools or AI-enabled apps",
				"Blogs or podcasts",
				"School (i.e., University, College, etc)",
				"Other online resources (e.g. standard search, forum, online community)",
				"Coding Bootcamp"
				]
		
		case "DevType":
			return [
				"Academic researcher",
				"AI/ML engineer",
				"Applied scientist",
				"Architect, software or solutions",
				"Cloud infrastructure engineer",
				"Cybersecurity or InfoSec professional",
				"Data engineer",
				"Data or business analyst",
				"Data scientist",
				"Database administrator or engineer",
				"Developer, AI apps or physical AI",
				"Developer, back-end",
				"Developer, desktop or enterprise applications",
				"Developer, embedded applications or devices",
				"Developer, front-end",
				"Developer, full-stack",
				"Developer, game or graphics",
				"Developer, mobile",
				"Developer, QA or test",
				"DevOps engineer or professional",
				"Engineering manager",
				"Financial analyst or engineer",
				"Founder, technology or otherwise",
				"Product manager",
				"Project manager",
				"Retired",
				"Senior executive (C-suite, VP, etc.)",
				"Student",
				"Support engineer or analyst",
				"System administrator",
				"UX, Research Ops or UI design professional",
			]
		
		case "LanguageHaveWorkedWith":
			return [
				"Ada",
				"Assembly",
				"Bash/Shell (all shells)",
				"C",
				"C#",
				"C++",
				"COBOL",
				"Dart",
				"Delphi",
				"Elixir",
				"Erlang",
				"F#",
				"Fortran",
				"GDScript",
				"Go",
				"Groovy",
				"HTML/CSS",
				"Java",
				"JavaScript",
				"Kotlin",
				"Lisp",
				"Lua",
				"MATLAB",
				"MicroPython",
				"OCaml",
				"Perl",
				"PHP",
				"PowerShell",
				"Prolog",
				"Python",
				"R",
				"Ruby",
				"Rust",
				"Scala",
				"SQL",
				"Swift",
				"TypeScript",
				"VBA",
				"Visual Basic (.Net)",
				"Zig",
				"Mojo",
				"Gleam"
			]
		
		case "DatabaseHaveWorkedWith":
			return [
				"BigQuery",
				"Cassandra",
				"Cloud Firestore",
				"Cosmos DB",
				"Databricks SQL",
				"Datomic",
				"DuckDB",
				"DynamoDB",
				"Elasticsearch",
				"Firebase Realtime Database",
				"H2",
				"IBM DB2",
				"InfluxDB",
				"MariaDB",
				"Microsoft Access",
				"Microsoft SQL Server",
				"MongoDB",
				"MySQL",
				"Neo4j",
				"Oracle",
				"PostgreSQL",
				"Redis",
				"Snowflake",
				"SQLite",
				"Supabase",
				"ClickHouse",
				"CockroachDB",
				"Amazon Redshift",
				"Pocketbase",
				"Valkey",
			]

		case "PlatformHaveWorkedWith":
			return [
				"Amazon Web Services (AWS)",
				"Ansible",
				"APT",
				"Bun",
				"Cargo",
				"Chocolatey",
				"Cloudflare",
				"Composer",
				"Datadog",
				"Digital Ocean",
				"Docker",
				"Firebase",
				"Google Cloud",
				"Gradle",
				"Heroku",
				"Homebrew",
				"IBM Cloud",
				"Kubernetes",
				"Make",
				"Maven (build tool)",
				"Microsoft Azure",
				"MSBuild",
				"Netlify",
				"New Relic",
				"Ninja",
				"npm",
				"NuGet",
				"Pacman",
				"Pip",
				"pnpm",
				"Podman",
				"Poetry",
				"Prometheus",
				"Railway",
				"Splunk",
				"Supabase",
				"Terraform",
				"Vercel",
				"Vite",
				"Webpack",
				"Yandex Cloud",
				"Yarn"
			]
		
		case "WebframeHaveWorkedWith":
			return [
				"Angular",
				"AngularJS",
				"ASP.NET",
				"ASP.NET Core",
				"Astro",
				"Blazor",
				"Deno",
				"Django",
				"Drupal",
				"Express",
				"FastAPI",
				"Fastify",
				"Flask",
				"jQuery",
				"Laravel",
				"NestJS",
				"Next.js",
				"Node.js",
				"Nuxt.js",
				"Phoenix",
				"React",
				"Ruby on Rails",
				"Spring Boot",
				"Svelte",
				"Symfony",
				"Vue.js",
				"WordPress",
				"Axum"
			]

		case "DevEnvsHaveWorkedWith":
			return [
				"Aider",
				"Android Studio",
				"Bolt",
				"Claude Code",
				"Cline and/or Roo Cursor",
				"Eclipse",
				"IntelliJ IDEA",
				"Jupyter Notebook/JupyterLab",
				"Lovable.dev",
				"Nano",
				"Neovim",
				"Notepad++",
				"PhpStorm",
				"PyCharm",
				"Rider",
				"RustRover",
				"Sublime Text",
				"Trae",
				"Vim",
				"Visual Studio",
				"Visual Studio Code",
				"VSCodium",
				"WebStorm",
				"Windsurf",
				"Xcode",
				"Zed"
			]

		case "EdLevel":
			return [
				"Primary/elementary school",
				"Other (please specify):",
				"Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",
				"Some college/university study without earning a degree",
				"Associate degree (A.A., A.S., etc.)",
				"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",
				"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",
				"Professional degree (JD, MD, Ph.D, Ed.D, etc.)"
			]

		case "AISelect":
			return [
				"Yes, I use AI tools daily",
				"Yes, I use AI tools weekly",
				"Yes, I use AI tools monthly or infrequently",
				"No, but I plan to soon",
				"No, and I don't plan to"
				]
	return None