apiVersion: 1

groups:
  - orgId: 1
    name: cpu-alerts
    folder: alerts
    interval: 60s
    rules:
      - uid: high_cpu_alert
        title: High CPU Usage
        condition: B

        data:
          - refId: A
            datasourceUid: prometheus-uid
            relativeTimeRange:
              from: 300
              to: 0
            model:
              expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
              interval: ""
              refId: A
          
          - refId: B
            datasourceUid: "__expr__"
            model:
              type: reduce
              expression: A     # refers to previous query
              reducer: max      # reduce function

        noDataState: NoData
        execErrState: Error
        for: 2m

        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for 2 minutes"

        labels:
          severity: critical

        isPaused: false
        